### ISSUE TITLE
Issue passing addresses from client to runtime

### ISSUE THREAD

**Issue by vishwa-raman** [oasislabs/oasis-rs#184]
Please look at branch `vishwa/add/erc20` in`tutorials` for an example where this manifests.

When you run the client test script you will see the following in the console,
```
  console.log test/service.spec.ts:42
    Error: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: byte array, expected an array of length 20"), offset: 0 }', src/libcore/result.rs:999:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

        at Function.<anonymous> (/tutorials/erc20/app/node_modules/@oasislabs/service/src/rpc.ts:65:17)
        at step (/tutorials/erc20/app/node_modules/node_modules/tslib/tslib.es6.js:99:23)
        at Object.next (/tutorials/erc20/app/node_modules/node_modules/tslib/tslib.es6.js:80:53)
        at fulfilled (/tutorials/erc20/app/node_modules/node_modules/tslib/tslib.es6.js:70:58)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

And chain output -
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: byte array, expected an array of length 20"), offset: 0 }', src/libcore/result.rs:999:5
```

**Comment by armaniferrante** [comment]
I can reproduce.

Enum generated by oasis-build:

`enum RpcPayload { get_count(), accept_addr((Address,)), }`

Data field in the runtime:

`Some([162, 102, 109, 101, 116, 104, 111, 100, 107, 97, 99, 99, 101, 112, 116, 95, 97, 100, 100, 114, 103, 112, 97, 121, 108, 111, 97, 100, 129, 84, 40, 142, 126, 28, 198, 9, 98, 244, 13, 77, 120, 41, 80, 71, 14, 55, 5, 197, 172, 244])`

Cbor decoding (in javascript) of that data field:

```
{ method: 'accept_addr',
  payload:
   [ Uint8Array [
       40,
       142,
       126,
       28,
       198,
       9,
       98,
       244,
       13,
       77,
       120,
       41,
       80,
       71,
       14,
       55,
       5,
       197,
       172,
       244 ] ] }
```

**Comment by armaniferrante** [comment]
The issue is that the Address type can't deserialize itself from a byte array. So changing the client from
```
await service.accept_addr(
		oasis.utils.bytes.parseHex('0x288e7e1cc60962f40d4d782950470e3705c5acf4')
	  );
```
to

```
await service.accept_addr(
[
       40,
       142,
       126,
       28,
       198,
       9,
       98,
       244,
       13,
       77,
       120,
       41,
       80,
       71,
       14,
       55,
       5,
       197,
       172,
       244 ]
	  );
```

Fixes the problem.

@nhynes should we change the Address type to be able to deserialize itself from a byte array?

I.e., first check the length and if it's 20, then go ahead and treat it like an array.

**Comment by vishwa-raman** [comment]
This is great! Thank you. Unblocks my ERC20 testing. Thanks @armaniferrante!

**Comment by armaniferrante** [comment]
Note that we get the same error when replacing `Address` with `Vec<u8>` in the service.

```
ErrorImpl { code: Message("invalid type: byte array, expected a sequence"), offset: 0 }', src/libcore/result.rs:1051:5
```

Cbor encoding on the client side as an `Array` instead of a `Uint8Array` also resolves this. While forcing the client to send a fixed length `Array` for an `Address` makes sense, it seems wrong for `Vec<u8>`.

**Comment by nhynes** [comment]
`Uint8Array` is [special cased](https://github.com/paroga/cbor-js/blob/65dc49611107db83aff8308a6b381f4d7933824b/cbor.js#L158). It'd probably need to be `serde_bytes`ed to work for `Vec<u8>`

**Comment by armaniferrante** [comment]
Feel free to close if you dont wan't to use `serde_bytes`. This needs a client change regardless.

**Comment by nhynes** [comment]
serde_bytes is correct. I can add this feature with not too much difficulty, so I'll leave it open. It's not a p0, though.
